export const TERMS = [
  "CARE COMPARE IS NOT RESPONSIBLE OR LIABLE FOR ANY USER DECISION REGARDING MEDICAL CARE. WE DO NOT CONTROL OR ARE RESPONSIBLE FOR \n" +
  "USERS HEALTH AND MEDICAL DECISIONS. TO THE FULLEST EXTENT OF PERMITTED BY APPLICABLE LAWS, ON BEHALF OF OUR TEAM, EXCLUDE AND DISCLAIM \n" +
  "LIABILITY FOR ANY LOSSES AND EXPENSES OF WHATEVER NATURE AND HOWSOEVER ARISING AND INCLUDING WITHOUT LIMITATION ANY DIRECT, INDIRECT, \n" +
  "  GENERAL, SPECIAL, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES; LOSS OF USE; LOSS OF DATA; LOSS CAUSED BY VIRUS; LOSS OF INCOME OR PROFIT;\n" +
  "  LOSS OF OR DAMAGE TO PROPERTY; CLAIMS OF THIRD PARTIES OR OTHER LOSSES OF ANY TYPE."
]
