// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:579bb6d6-5126-4dbe-8c71-9aeae185cad7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_W0chPrnwp",
    "aws_user_pools_web_client_id": "60jcsvinejvp4se9kisjlkucti",
    "oauth": {}
};


export default awsmobile;
